## Overall my functions do what the assignment asks.

## The first makes an object that's a matrix
## capable of caching the inverse of itself.
## The second function calculates the inverse
## of the matrix or Otherwise retrieves
## the cached calculation of the matrix if it's
## been previous calculated.

## The makeCacheMatrix function essentially has
## 4 functions inside it: 1) set matrix 2) get
## the matrix 3) set the inverse of the matrix
## 4) get the inverse of the matrix. "m" is the
## matrix and "i" is the inverse of matrix "m".
## The four functions are subsequently defined
## with the code after "m" and "i" are defined.
## The list function at the end creates a new
## object with the objects generated by the four
## functions above it and assigns each to an
## element within the list.

makeCacheMatrix <- function(m = matrix()) {
  i <- NULL
  set <- function(y) {
    m <<- y
    i <<- NULL
  }
  get <- function() m
  setinverse <- function(inverse) i <<- inverse
  getinverse <- function() i
  list(set = set,
       get = get,
       setinverse = setinverse,
       getinverse = getinverse)
}

## The cacheSolve function is designed to 
## calculate the inverse of the matrix called
## in the makeCacheMatrix function or otherwise
## retrieve the cached result from a previous
## calculation. A "..." is included so a caller
## can pass any other arguments they want to
## the function."i" is set equal to the get
## inverse function from the makeCacheMatrix
## function and an is.null function is included
## to check if a cached result already exists
## (i.e. it checks to see if i = NULL).  If the
## result is FALSE it retrieves the cached result 
## and displays a message saying as much.
## Otherwise the inverse is solved for by the
## solve function (which wasn't present in
## the makeCacheMatrix function).

cacheSolve <- function(m, ...) {
  i <- m$getinverse()
  if (!is.null(i)) {
    message("retrieving cached result")
    return(i)
  }
  result <- m$get()
  i <- solve(result, ...)
  m$setinverse(i)
  i
}
